### ISSUE TITLE
behind http proxy ?

### ISSUE THREAD

**Issue by keltakmaster** [dmitriykuptsov/soho-vpn-over-tls#3]
Hi! Is there a way to use this behind an http proxy with authentication?
Thanks!

**Comment by dmitriykuptsov** [comment]
Hi,

Take a look at the proxy branch. Configure the server IP with the IP address of you proxy, and then configure the PROXY_TARGET_HOST and PROXY_TARGET_PORT. Also set the proxy password in PROXY_PASSWORD

However, I should warn that I did not yet test the implementation, but assume that it should work fine.

**Comment by keltakmaster** [comment]
Thanks so much! I'll give it a try!! Keep up the good work!
